version: "3.9" 
services:
  build:
    image: circleci/golang:1.15      
    working_dir: "/usr/src/app"
    environment:
      GOOS: linux
      GARCH: amd64
      CGO_ENABLED: 0
    volumes:
    - "${PWD}:/usr/src/app"    
    command: "./build.sh"
  test:
    image: circleci/golang:1.15      
    working_dir: "/usr/src/app"
    volumes:
    - "${PWD}:/usr/src/app"    
    command: "./test.sh"